name: Continuous Integration
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  pull_request:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Use Node.js 12.8
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Lint - Eslint
        run: npm run lint

      - name: Format - Prettier
        run: npm run format:check

      - name: Test
        run: npm test
